/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ufes.delivery.view;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author raphael
 */
public class TelaLoginView extends javax.swing.JPanel implements ILoginView{

    /**
     * Creates new form TelaLoginView
     */
    public TelaLoginView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dadosDeAcessoPanel = new javax.swing.JPanel();
        nomeLbl = new javax.swing.JLabel();
        senhaLbl = new javax.swing.JLabel();
        nomeTxt = new javax.swing.JTextField();
        senhaTxt = new javax.swing.JPasswordField();
        cadastrarBtn = new javax.swing.JButton();
        cancelarBtn = new javax.swing.JButton();
        acessarBtn = new javax.swing.JButton();

        dadosDeAcessoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados de Acesso"));

        nomeLbl.setText("Nome de Usuário");

        senhaLbl.setText("Senha");

        nomeTxt.addActionListener(this::nomeTxtActionPerformed);

        javax.swing.GroupLayout dadosDeAcessoPanelLayout = new javax.swing.GroupLayout(dadosDeAcessoPanel);
        dadosDeAcessoPanel.setLayout(dadosDeAcessoPanelLayout);
        dadosDeAcessoPanelLayout.setHorizontalGroup(
            dadosDeAcessoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosDeAcessoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dadosDeAcessoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeLbl)
                    .addComponent(senhaLbl))
                .addGap(18, 18, 18)
                .addGroup(dadosDeAcessoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(senhaTxt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dadosDeAcessoPanelLayout.setVerticalGroup(
            dadosDeAcessoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosDeAcessoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dadosDeAcessoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLbl)
                    .addComponent(nomeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dadosDeAcessoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaLbl)
                    .addComponent(senhaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        cadastrarBtn.setText("Cadastrar Usuário");
        cadastrarBtn.addActionListener(this::cadastrarBtnActionPerformed);

        cancelarBtn.setText("Cancelar");

        acessarBtn.setText("Acessar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(acessarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadastrarBtn))
                    .addComponent(dadosDeAcessoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(dadosDeAcessoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarBtn)
                    .addComponent(cancelarBtn)
                    .addComponent(acessarBtn))
                .addContainerGap(11, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nomeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTxtActionPerformed

    private void cadastrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acessarBtn;
    private javax.swing.JButton cadastrarBtn;
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JPanel dadosDeAcessoPanel;
    private javax.swing.JLabel nomeLbl;
    private javax.swing.JTextField nomeTxt;
    private javax.swing.JLabel senhaLbl;
    private javax.swing.JPasswordField senhaTxt;
    // End of variables declaration//GEN-END:variables

    @Override
    public JButton getAcessarButton() {
       return this.acessarBtn;
    }

    @Override
    public JButton getCancelarButton() {
        return this.cancelarBtn;
    }

    @Override
    public JButton getCadastrarUsuarioButton() {
        return this.cadastrarBtn;
    }

    @Override
    public JTextField getNomeUsuario() {
        return this.nomeTxt;
    }

    @Override
    public JPasswordField getSenhaUsuario() {
        return this.senhaTxt;
    }

    @Override
    public JPanel getJanelaPrincipal() {
        return this.dadosDeAcessoPanel;
    }

    
}
